name: deforum
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - ipykernel
  - nodejs
  - opencv
  - pip
  - pip:
    - torch
    - requests
    - itk==5.3.0
    - itkwidgets[all]==1.0a20
    - imjoy-jupyterlab-extension
    - -r requirements.txt